language: ruby
sudo: required
services:
  - docker
env:
  - DOCKER=0
  - DOCKER=1
before_install:
  - bash -c '[ "$DOCKER" = "1" ] && sudo docker pull dwilkie/dynamize:spec || echo "DOCKER=$DOCKER. Skipping docker pull"'
script:
  - bash -c '[ "$DOCKER" = "1" ] && sudo docker run --rm dwilkie/dynamize:spec /bin/sh -c "bundle exec rake" || bundle exec rake'
after_success:
  - bash -c '[ "$DOCKER" = "1" ] && git clone "https://github.com/$TRAVIS_REPO_SLUG.git" out && cd out && git config user.email "deploy@travis-ci.org" && git config user.name "Deployment Bot (from Travis CI)" && ls -la && ls $(pwd)/examples/templates && sudo docker run --rm -v $(pwd)/examples/templates:/tmp/dynamizer_templates:ro -v $(pwd)/examples/renderers:/tmp/dynamizer_renderers:ro -v $(pwd)/examples/data:/tmp/dynamizer_data:ro -v $(pwd):/tmp/dynamizer_output dwilkie/dynamize /bin/sh -c "bundle exec rake dynamizer:dynamize" && git status || echo "DOCKER=$DOCKER. Skipping deploy"'
