language: ruby
sudo: required
services:
  - docker
env:
  - DOCKER=0
  - DOCKER=1
before_install:
  - bash -c 'if [[ "${DOCKER}" == "1" ]]; then sudo docker pull dwilkie/dynamize:spec; fi'
script:
  - bash -c 'if [[ "${DOCKER}" == "1" ]]; then sudo docker run --rm dwilkie/dynamize:spec /bin/sh -c "bundle exec rake"; else bundle exec rake; fi'
after_success:
  - bash -c 'if [[ "${DOCKER}" == "1" ]]; then sudo docker run --rm dwilkie/dynamize /bin/sh -c "bundle exec rake dynamizer:dynamize && git status"; fi'
