language: ruby
sudo: required
services:
  - docker
env:
  - DOCKER=0
  - DOCKER=1
before_install:
  - bash -c 'if [[ "${DOCKER}" == "1" ]]; then sudo docker pull dwilkie/dynamize:spec; fi'
script:
  - bash -c 'if [[ "${DOCKER}" == "1" ]]; then sudo docker run --rm dwilkie/dynamize:spec /bin/sh -c "bundle exec rake"; else bundle exec rake; fi'
after_success:
  - [ "$DOCKER" = "1" ] && git clone "https://github.com/$TRAVIS_REPO_SLUG.git" out && cd out && ls
  - git config user.email "deploy@travis-ci.org"
  - git config user.name "Deployment Bot (from Travis CI)"
  - bash -c 'if [[ "${DOCKER}" == "1" ]]; then sudo docker run --rm -v $(pwd)/examples/templates:/tmp/dynamizer_templates:ro -v $(pwd)/examples/renderers:/tmp/dynamizer_renderers:ro -v $(pwd)/examples/data:/tmp/dynamizer_data:ro -v $(pwd):/tmp/dynamizer_output dwilkie/dynamize dwilkie/dynamize /bin/sh -c "bundle exec rake dynamizer:dynamize"; fi'
  - git add .
  - git status
